<?php

namespace Database\Seeders;

use App\Models\CarBrand;
use App\Models\CarModel;
use Illuminate\Database\Seeder;

class CarModelSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $carBrands = [
            'Toyota' => [
                '4Runner',
                'Aristo',
                'Aurion',
                'Avalon',
                'Avensis',
                'Camry',
                'Camry Hybrid',
                'Camry Solara',
                'Carina',
                'Celica',
                'Celsior',
                'Coaster',
                'Corolla',
                'Corolla Verso',
                'Corona',
                'Cressida',
                'Cresta',
                'Crown',
                'Dyna',
                'Echo',
                'Fj Cruiser',
                'Fortuner',
                'Harrier',
                'Hiace',
                'Highlander',
                'Highlander Hybrid',
                'Hilux',
                'Innova',
                'Ipsum',
                'Land Cruiser',
                'Land Cruiser Prado',
                'Mr2',
                'Marino',
                'Mark li',
                'Matrix',
                'Paseo',
                'Prado',
                'Previa',
                'Prius',
                'Prius Plug-In',
                'Prius Plug-In Hybrid',
                'Prius C',
                'Prius V',
                'Rav4',
                'Rush',
                'Scion',
                'Sequoia',
                'Sienna',
                'Solara',
                'Sprinter',
                'Supra',
                'T100',
                'T100 Xtra',
                'Tacoma',
                'Tacoma Xtra',
                'Tercel',
                'Tiko',
                'Town Ace',
                'Truck Xtracab Sr5',
                'Tundra',
                'Tundramax',
                'Venza',
                'Vista',
                'Windom',
                'Xa',
                'Xtra',
                'Yaris'
            ],
            'Lexus' => [
                'Ct',
                'Es',
                'Es300',
                'Es330',
                'Es350',
                'Gs',
                'Gx',
                'Hs',
                'Is',
                'Is F',
                'Lfa',
                'Ls',
                'Ls Hybrid',
                'Lx',
                'Nx',
                'Rx',
                'Rx Hybrid',
                'Rx300',
                'Rx330',
                'Rx350',
                'Sc'
            ],
            'BMW' => [
                '1 Series',
                '3 Series',
                '320',
                '323',
                '325',
                '328',
                '330',
                '5 Series',
                '520',
                '525',
                '528',
                '530',
                '535',
                '540',
                '545',
                '550',
                '6 Series',
                '600',
                '640M',
                '645',
                '650',
                '7 Series',
                '730',
                '745',
                '750',
                '760',
                '8 Series',
                'Alpina B7',
                'E34',
                'E39',
                'E46',
                'E60',
                'F07',
                'F10',
                'F10 M5',
                'F11',
                'F30',
                'GT',
                'M',
                'M Roadster',
                'M3',
                'M4',
                'M5',
                'M6',
                'W212',
                'X1',
                'X3',
                'X4',
                'X5',
                'X5 M',
                'X6',
                'X6 M',
                'Z3',
                'Z4',
                'Z4 M',
                'Z4 M Roadster',
                'Z8'
            ],
            'Mercedes-Benz' => [
                '190E',
                '230E',
                '300CE',
                '300D',
                '300E',
                '300SD',
                '300SE',
                '300SL',
                '300TE',
                '400E',
                '400SE',
                '400SEL',
                '500E',
                '500SEC',
                '500SEL',
                '500SL',
                '600SEC',
                '600SEL',
                '600SL',
                'A150',
                'ACTROS 3331',
                'B-Class',
                'C-Class',
                'C250',
                'C280',
                'C300',
                'C320',
                'C350',
                'CL-Class',
                'CL65 AMG',
                'CLA',
                'CLK-Class',
                'CLS-Class',
                'E-Class',
                'E280',
                'E300',
                'E320',
                'E350',
                'E420',
                'E430',
                'E500',
                'G-Class',
                'G55 AMG',
                'GL-Class',
                'GLE 43',
                'GLK 350',
                'GLK-Class',
                'M-Class',
                'ML350',
                'ML400',
                'Other',
                'R-Class',
                'S-Class',
                'SL-Class',
                'SL65 AMG',
                'SLK-Class',
                'SLK55 AMG',
                'SLR McLaren',
                'SLS AMG',
                'SLS-Class',
                'Sprinter',
                'Sprinter 2500',
                'Sprinter 3500',
                'Viano',
                'W123',
                'W126',
                'W201',
                'W212'
            ],
            'Hyundai' => [
                'Accent',
                'Azera',
                'County',
                'Cupe',
                'Elantra',
                'Entourage',
                'Equus',
                'Excel',
                'Galloper',
                'Genesis',
                'Genesis Coupe',
                'Getz',
                'Grandeur',
                'H-1',
                'H100',
                'HED-5',
                'I30',
                'IX35',
                'IX55',
                'Kona',
                'Santa Fe',
                'Scoupe',
                'Sonata',
                'Tiburon',
                'Trajet',
                'Tucson',
                'Veloster',
                'Veracruz',
                'XG300',
                'XG350'
            ],
            'Volkswagen' => [
                'Amarok',
                'Beetle',
                'Bora',
                'CC',
                'Cabriolet',
                'Caddy',
                'Corrado',
                'Crafter',
                'Derby',
                'Eos',
                'Eurovan',
                'Fox',
                'GLI',
                'GTI',
                'Golf',
                'Golf III',
                'Jetta',
                'Jetta III',
                'Juke',
                'Multivan',
                'New Beetle',
                'Passat',
                'Phaeton',
                'Polo',
                'Quantum',
                'R32',
                'Rabbit',
                'Routan',
                'Scirocco',
                'Spacefox',
                'Tiguan',
                'Touareg',
                'Touareg 2',
                'Transporter',
                'Type 2',
                'Vanagon',
                'rio',
                'riolet'
            ],
            'Chevrolet' => [
                '1500',
                '2500',
                '3500',
                'APV',
                'Astro',
                'Avalanche',
                'Avalanche 1500',
                'Avalanche 2500',
                'Aveo',
                'Bel Air',
                'Beretta',
                'Blazer',
                'Camaro',
                'Caprice',
                'Caprice Classic',
                'Captiva',
                'Cavalier',
                'Citation',
                'Classic',
                'Cobalt',
                'Cobalt SS',
                'Colorado',
                'Corsica',
                'Corvair',
                'Corvair 500',
                'Corvette',
                'Cruze',
                'Epica',
                'Equinox',
                'Express',
                'Express 1500',
                'Express 2500',
                'Express 3500',
                'G-Series 1500',
                'G-Series 2500',
                'G-Series 3500',
                'G-Series G10',
                'G-Series G20',
                'G-Series G30',
                'HHR',
                'HHR Panel',
                'Impala',
                'Impala SS',
                'K5 Blazer',
                'LUV',
                'Lumina',
                'Lumina APV',
                'Malibu',
                'Malibu Maxx',
                'Metro',
                'Monte Carlo',
                'Monza',
                'Niva',
                'Prizm',
                'S10',
                'S10 Blazer',
                'SSR',
                'Silverado',
                'Silverado 1500',
                'Silverado 2500',
                'Silverado 3500',
                'Silverado 3500HD',
                'Silverado Hybrid',
                'Sonic',
                'Spark',
                'Sportvan G10',
                'Sportvan G20',
                'Sportvan G30',
                'Suburban',
                'Suburban 1500',
                'Suburban 2500',
                'Tahoe',
                'Tracker',
                'TrailBlazer',
                'Trailblazer',
                'Traverse',
                'Uplander',
                'Vega',
                'Venture',
                'Volt'
            ],
            'Mazda' => [
                '323',
                '6',
                '626',
                '929',
                'B-Series',
                'B-Series Plus',
                'B2000',
                'B2500',
                'B2600',
                'CX-5',
                'CX-7',
                'CX-9',
                'Familia',
                'GLC',
                'MAZDA6',
                'MPV',
                'MX-3',
                'MX-5',
                'MX-6',
                'Mazda2',
                'Mazda3',
                'Mazda5',
                'Mazda6',
                'Mazda6 5-Door',
                'Mazda6 Sport',
                'Mazdaspeed 3',
                'Mazdaspeed6',
                'Miata MX-5',
                'Millenia',
                'Navajo',
                'Protege',
                'Protege5',
                'RX-7',
                'RX-8',
                'Tribute'
            ],
            'Infiniti' => [
                'EX',
                'FX',
                'FX35',
                'G',
                'G25',
                'G35',
                'G37',
                'I',
                'I30',
                'I35',
                'IPL G',
                'J',
                'JX',
                'M',
                'Q',
                'QX',
                'QX4',
                'QX56'
            ],
            'Nissan' => [
                '200SX',
                '240SX',
                '280ZX',
                '300ZX',
                '350Z',
                '350Z Roadster',
                '370Z',
                'Almera',
                'Altima',
                'Armada',
                'Bluebird',
                'Canter',
                'Cefiro',
                'Civilian',
                'Cube',
                'Datsun/Nissan Z-car',
                'Frontier',
                'GT-R',
                'JUKE',
                'Kicks',
                'Leaf',
                'Maxima',
                'Murano',
                'NV1500',
                'NV2500',
                'NV3500',
                'NX',
                'Navara',
                'Pathfinder',
                'Pathfinder Armada',
                'Patrol',
                'Primera',
                'Qashqai',
                'Quest',
                'Rogue',
                'Sentra',
                'Stanza',
                'Sunny',
                'Teana',
                'Terrano',
                'Tiida',
                'Titan',
                'Urvan',
                'Versa',
                'X-Trail',
                'Xterra',
                'cube'
            ],
            'Kia' => [
                'Amanti',
                'Bongo',
                'Bongo',
                'Borrego',
                'Cadenza',
                'Carens',
                'Carnival',
                'Cerato',
                'Credos/Clarus',
                'Forte',
                'Frontier',
                'Magentis',
                'Mentor',
                'Mohave/Borrego',
                'Opirus',
                'Optima',
                'Picanto',
                'Pride',
                'Rio',
                'Rio5',
                'Rondo',
                'Sedona',
                'Sephia',
                'Sorento',
                'Soul',
                'Spectra',
                'Spectra5',
                'Sportage',
                'Stinger'
            ],
            'Audi' => [
                '100',
                '200',
                '4000',
                '4000CS Quattro',
                '4000s',
                '4000s Quattro',
                '5000CS',
                '5000CS Quattro',
                '5000S',
                '80',
                '80/90',
                '90',
                'A3',
                'A4',
                'A5',
                'A6',
                'A7',
                'A8',
                'Allroad',
                'Cabriolet',
                'Coupe GT',
                'Coupe Quattro',
                'Q5',
                'Q7',
                'Q8',
                'Quattro',
                'R8',
                'RS 4',
                'RS 6',
                'RS2',
                'RS4',
                'RS6',
                'S3',
                'S4',
                'S5',
                'S6',
                'S8',
                'TT',
                'V8',
                'riolet'
            ],
            'Jeep' => [
                'Cherokee',
                'Comanche',
                'Commander',
                'Compass',
                'Grand Cherokee',
                'Liberty',
                'Patriot',
                'Wrangler'
            ],
            'Ford' => [
                'Aerostar',
                'Aspire',
                'B-Max',
                'Bronco',
                'Bronco II',
                'C-MAX Hybrid',
                'Cargo 3535D',
                'Cargo 3536M',
                'Club Wagon',
                'Contour',
                'Country',
                'Courier',
                'Crown Victoria',
                'E-350 Super Duty',
                'E-350 Super Duty Van',
                'E-Series',
                'E150',
                'E250',
                'E350',
                'EXP',
                'EcoSport',
                'Econoline E150',
                'Econoline E250',
                'Econoline E350',
                'Edge',
                'Escape',
                'Escort',
                'Escort ZX2',
                'Everest',
                'Excursion',
                'Expedition',
                'Expedition EL',
                'Explorer',
                'Explorer Sport',
                'Explorer Sport Trac',
                'F-250 Super Duty',
                'F-350 Super Duty',
                'F-Series',
                'F-Series Super Duty',
                'F150',
                'F250',
                'F350',
                'F450',
                'Fairlane',
                'Falcon',
                'Festiva',
                'Fiesta',
                'Figo',
                'Five Hundred',
                'Flex',
                'Focus',
                'Focus ST',
                'Freestar',
                'Freestyle',
                'Fusion',
                'GT',
                'GT500',
                'Galaxie',
                'LTD',
                'LTD Crown Victoria',
                'Laser',
                'Lightning',
                'Model T',
                'Mondeo',
                'Mondeo 3',
                'Mondeo 4',
                'Mustang',
                'Probe',
                'Ranger',
                'Scorpio',
                'TH!NK',
                'Taurus',
                'Taurus X',
                'Tempo',
                'Th!nk',
                'Thunderbird',
                'Torino',
                'Transit Connect',
                'Windstar',
                'ZX2'
            ],
            'Mitsubishi' => [
                'Canter',
                'Carisma',
                'Chariot',
                'Delica',
                'Diamante',
                'Eclipse',
                'Fuso',
                'Fuso Rosa',
                'Galant',
                'Hover',
                'L200',
                'L300',
                'Lanser',
                'Montero',
                'Nativa',
                'Outlander',
                'Pajero',
                'RVR',
                'Rosa',
                'Sigma'
            ],
            'Chrysler' => [
                '200',
                '300C'
            ],
            'Man' => [
                'LE 140',
                'TGX'
            ],
            'Volvo' => [
                '740',
                '760',
                '780',
                '850',
                '940',
                '960',
                'C30',
                'C70',
                'EURO 4',
                'FH 420',
                'FH 460',
                'FH 480',
                'FH 500',
                'FH12',
                'FM 520',
                'FM 550',
                'FM 600',
                'FM 660',
                'FM 700',
                'FM 750',
                'S40',
                'S60',
                'S70',
                'S90',
                'V40',
                'V60',
                'V70',
                'V90',
                'XC60',
                'XC70',
                'XC90'
            ],
            'Lada' => [
                '2101',
                '2102',
                '2103',
                '2104',
                '2105',
                '2106',
                '2107',
                '2108',
                '2109',
                '21099',
                '2110',
                '2111',
                '2112',
                '2115',
                'Granta',
                'Kalina',
                'Largus',
                'Niva',
                'Priora',
                'Samara',
                'VAZ-2107',
                'VAZ-2108',
                'VAZ-2109',
                'VAZ-21099',
                'VAZ-2110',
                'VAZ-2111',
                'VAZ-2112',
                'Vesta',
                'XRay'
            ],
            'Opel' => [
                'Agila',
                'Antara',
                'Astra',
                'Calibra',
                'Combo',
                'Corsa',
                'Frontera',
                'Insignia',
                'Meriva',
                'Mokka',
                'Montarey',
                'Movano',
                'Omega',
                'Senator',
                'Signum',
                'Sintra',
                'Tigra',
                'Vectra',
                'Vita',
                'Zafira'
            ],
            'Waz' => [
                '2106',
                '2107',
                '2110'
            ],
            'Dodge' => [
                'Caliber',
                'Caravan',
                'Charger',
                'Magnum'
            ],
            'Honda' => [
                'Accord',
                'CR-V',
                'Civic',
                'Fit',
                'Integra',
                'Odyssey',
                'Pilot',
                'Ridgeline'
            ],
            'Daf' => [
                '45220',
                '460',
                '480',
                'CF',
                'FX 95'
            ],
            'Peugeot' => [
                '108',
                '206',
                '208',
                '301',
                '308',
                '405',
                '407',
                '408',
                '508',
                '607'
            ],
            'Kamaz' => [
                '4310',
                '5320',
                '5410',
                '5511',
                '6520',
                '6520',
                'Euro 3',
                'Shalanda'
            ],
            'Citroen' => [
                'C-Elysee'
            ],
            'Zil' => [
                '130',
                '131',
                '133',
                '157',
                '4331'
            ],
            'Renault' => [
                'Clio',
                'Duster',
                'Espace',
                'Europa 19',
                'Laguna 1',
                'Megane 2',
                'Megane CC',
                'Megane GT',
                'Phase I',
                'Phase II',
                'Safrane',
                'Trafic',
                'Twingo'
            ],
            'Daewoo' => [
                'Aveo',
                'Cielo',
                'Damas',
                'Espero',
                'Gentra',
                'Kalos',
                'Lacetti',
                'Lanos',
                'Leganza',
                'Magnus',
                'Matiz',
                'Musso MJ',
                'Nexia',
                'Nubira',
                'Prince',
                'Racer',
                'Tacuma',
                'Tico',
                'Tosca',
                'Winstorm'
            ],
            'Howo' => [
                'Sinotruk'
            ],
            'Uaz' => [
                '2206',
                '452',
                '462',
                '469',
                'Profi'
            ],
            'Ural' => [
                '4320',
                '5557'
            ],
            'Maz' => [
                'Samosval'
            ],
            'Iveco' => [
                'Daily',
                'EuroCargo',
                'Magirus',
                'Stralis 450',
                'Trakker'
            ],
            'Gaz' => [
                '21',
                '24',
                '31',
                '3110',
                '52',
                '5204',
                '53',
                '66',
                'Gazel',
                'M20(Pobeda)',
                'ZIM-12'
            ],
            'Kogel' => [
                'Cargo',
                'Combi',
                'Euro Trailer',
                'Light',
                'Mayan',
                'Mega',
                'Port',
                'Swap'
            ],
            'Scania' => [
                'Truck'
            ],
            'Forland' => [
                'H2',
                'H3'
            ],
            'Chery' => [
                'A19',
                'Amulet',
                'Arrizo 7',
                'Bonus',
                'CrossEastar',
                'Eastar',
                'Fora',
                'IndiS',
                'Karry',
                'Kimo',
                'M11',
                'QQ',
                'QQ6',
                'Tiggo',
                'Very'
            ],
            'Mtz' => [
                '80',
                '82',
                'T-28'
            ],
            'Land Rover' => [
                'Defender',
                'Discovery',
                'Freelander',
                'Range Rover'
            ],
            'Golden Dragon' => [
                'XML6125CC',
                'XML6723',
                'XML6901'
            ],
            'Changan' => [
                'Alsvin',
                'Benni',
                'CS35',
                'CS75',
                'CX20',
                'CX30',
                'Chana Oushang',
                'Chana Ruixing',
                'Chana Star',
                'Chana Taurustar',
                'Eado',
                'Eado EV',
                'Raeton',
                'Z-Shine'
            ],
            'Jcb' => [
                '3CX Compact',
                '3CX ECO',
                '3CX Pothole Master',
                '4CX ECO',
                '5CX Wastemaster',
                'ICX',
                'ICXT',
                'Pilingmaster',
                'Polemaster Plus'
            ],
            'Xcmg' => [
                '25',
                '500',
                'LW300F',
                'LW500F',
                'ZL50'
            ],
            'Schmitz' => [
                'Cargobull',
                'S01',
                'SAF',
                'SCB S3T',
                'SCF-24G',
                'SCS',
                'SCS 24',
                'SCS 24/L-13.62EB',
                'SKO',
                'SKO-24',
                'SKO-24L',
                'SLX'
            ],
            'Fekon' => [
                'FK150-8G',
                'FK200-14G'
            ],
            'Tadano Faun' => [
                'Atf 60-4'
            ],
            'Fiat' => [
                'Albea',
                'Brava',
                'Bravo',
                'Doblo',
                'Ducato',
                'Fiorino',
                'Punto',
                'Uno'
            ],
            'Prisep' => [
                'Polprisep'
            ],
            'Container' => [
                'Morskoy'
            ],
            'Saipa' => [
                'Saba',
                'Tiba',
                'Zamyad'
            ],
            'Iž' => [
                'Planeta',
                'Planeta 4',
                'Planeta 5',
                'Ýupiter',
                'Ýupiter 3',
                'Ýupiter 4'
            ],
            'Saab' => [
                'Scania'
            ],
            'Isuzu' => [
                'Elf',
                'Forward',
                'Giga',
                'Trooper'
            ],
            'New Holland' => [
                'L160'
            ],
            'Yamaha' => [
                'Artistic'
            ],
            'Москвич' => [
                '408',
                '412'
            ],
            'Cmc' => [
                'Veryca',
                'Z7'
            ],
            'Pontiac' => [
                'Aztek',
                'Bonneville',
                'Firebird',
                'Solstice',
                'Solstice'
            ],
            'Kuba' => [
                'Eland 200'
            ],
            'Tofaş' => [
                'Dogan',
                'Kartal',
                'Şahin'
            ],
            'Liugong' => [
                'Excavator',
                'Forklift',
                'Roller'
            ],
            'Zaz' => [
                '965',
                '965A',
                '966',
                '968',
                '968m'
            ],
            'Skoda' => [
                'Citigo',
                'Fabia',
                'Octavia',
                'Rapid',
                'Roomster',
                'Superb',
                'Yeti'
            ],
            'Subaru' => [
                'BRZ',
                'Impreza WRX',
                'Impreza XV',
                'Levorg',
                'Outback'
            ],
            'Caterpillar' => [
                'Dozer',
                'Excavator',
                'Forklift'
            ],
            'Camc' => [
                'HN 3601',
                'HN3250P34C6M',
                'HN3310P38C3M'
            ],
            'Zonda' => [
                'Awtobus'
            ],
            'Ssangyong' => [
                'Actyon',
                'Actyon Sports',
                'Chairman W',
                'Korando',
                'Kyron',
                'Musso',
                'Rexton W',
                'Rodius/Stavic',
                'Tivoli'
            ],
            'Lifan' => [
                '320',
                '520',
                '620',
                '720',
                '820',
                'X50',
                'X60',
                'X80'
            ],
            'Buick' => [
                'Buick Verano',
                'Cascada',
                'Enclave',
                'Encore',
                'Envision',
                'GL8',
                'LaCrosse',
                'Regal'
            ],
            'Raf' => [
                '2203',
                '22038',
                '977'
            ],
            'Alfa Romeo' => [
                '145',
                '156',
                '159',
                '166',
                '4C Spider',
                '8C Competizione',
                'Brera',
                'Giulia',
                'Giulietta',
                'MiTo',
                'Stelvio'
            ],
            'Byd' => [
                'F0',
                'F3',
                'F5',
                'F6',
                'G6',
                'L3',
                'S6',
                'S7',
                'Song',
                'Yuan'
            ],
            'Belarus' => [
                '320',
                '422',
                '550',
                '622',
                '80.1',
                '923'
            ],
            'Porsche' => [
                '356',
                '911',
                '912',
                '914',
                '918 Spyder',
                '924',
                '928',
                '930',
                '944',
                '959',
                '964',
                '968',
                '991',
                '993',
                '996',
                '997',
                'Boxster',
                'Carrera GT',
                'Cayenne',
                'Cayman',
                'Macan',
                'Panamera'
            ],
            'Brilliance' => [
                'H220',
                'H230',
                'H3',
                'H320',
                'H330',
                'H530',
                'V3',
                'V5',
                'V6',
                'V7'
            ],
            'Daihatsu' => [
                'Copen',
                'Cuore',
                'Gran Move',
                'Materia',
                'Sirion',
                'Terios',
                'Trevis',
                'YRV'
            ],
            'Roewe' => [
                '350',
                '360',
                '550',
                '750',
                '850',
                '950',
                'E50',
                'RX3',
                'RX5',
                'RX7',
                'RX8',
                'W5',
                'i5',
                'i6'
            ],
            'Mg' => [
                '3',
                '350',
                '5',
                '550',
                '6',
                '750',
                'F',
                'GS',
                'MGB',
                'Maestro',
                'Metro',
                'Midget',
                'Montego',
                'RV8',
                'TF',
                'Xpower SV',
                'ZR',
                'ZS',
                'ZT'
            ],
            'Mini' => [
                '5-door Hatch',
                'Clubman',
                'Convertible',
                'Cooper S',
                'Hatch/Hardtop',
                'Paceman'
            ],
            'Suzuki' => [
                'APV',
                'Alto',
                'Baleno',
                'Carry',
                'Celerio',
                'Ciaz',
                'Dzire',
                'Ertiga',
                'Every',
                'Every Landy',
                'Ignis',
                'Jimny',
                'Landy',
                'Lapin',
                'SX4',
                'Solio',
                'Swift',
                'Vitara',
                'Wagon R'
            ],
            'Komatsu' => [
                '830E-AC',
                '960E-2K',
                'D155AX-8',
                'D275AX-5',
                'D375A-6',
                'D475A-5E0',
                'D51PXi-22',
                'D65EX-17',
                'D65PX-17',
                'FH50-2',
                'GD655-5',
                'GD655-6',
                'HB205LC-3',
                'HB215LC-3',
                'HD605-8',
                'HD785-7',
                'HM400-5',
                'HM400-5',
                'PC138USLC-11',
                'PC2000-8',
                'PC200LC-8',
                'PC210LC-11',
                'PC360LC-11',
                'PC490LC-11',
                'WA1200',
                'WA380-7',
                'WA420-3',
                'WA470-8',
                'WA500-7',
                'WA600-8',
                'WA900-3'
            ],
            'International' => [
                '5000i / PayStar',
                '7000 / WorkStar',
                '8000 / TransStar',
                '9000i',
                'CV Series',
                'DuraStar',
                'HV Series',
                'HX Series',
                'LT Series',
                'MV Series',
                'ProStar',
                'RH Series'
            ],
            'Smart' => [
                'Forfour',
                'Fortwo',
                'Roadster'
            ],
            'John' => [
                'Deere'
            ],
            'Ppm' => [
                '1409',
                '18.01',
                '2007',
                '25.09',
                '3201 MOBILKRAN',
                'A 230',
                'A 350',
                'A300',
                'A450',
                'A580',
                'A780',
                'ATT 280',
                'ATT 350',
                'ATT 380',
                'ATT 390',
                'ATT 400',
                'ATT 600',
                'ATT 680',
                'C 580',
                'C580',
                'RT 1417',
                'TEREX ATT340',
                'TEREX ATT400'
            ],
            'Gmc' => [
                'Acadia',
                'Envoy',
                'Jimmy',
                'Safari',
                'Sierra',
                'Terrain',
                'Yukon'
            ],
            'Lincoln' => [
                'Aviator',
                'Continental',
                'Corsair',
                'MKS',
                'MKX',
                'MKZ',
                'Mark',
                'Navigator'
            ],
            'Jawa' => [
                '300',
                'Forty Two',
                'Perak'
            ],
            'Geely' => [
                'CK'
            ],
            'Seat' => [
                'Alhambra',
                'Arona',
                'Arosa',
                'Cordoba',
                'Ibiza',
                'Marbella',
                'Toledo'
            ],
            'Jungheinrich' => [
                'DFG 25',
                'DFG435S',
                'EFG 220',
                'EKS',
                'EKX',
                'ERC 216',
                'ERE 120'
            ],
            'Foton Lovol' => [
                'FL935E'
            ],
            'Case' => [
                'STX325 Accusteer',
                'STX375 Quadtrac',
                'STX380 Quadtrac',
                'STX440 Quadtrac',
                'STX450 Quadtrac',
                'STX480 Quadtrac',
                'STX500 Quadtrac',
                'STX530 Quadtrac',
                'STX535 Quadtrac',
                'STX550 Quadtrac',
                'STX600 Quadtrac'
            ],
            'Foton' => [
                'ETX',
                'Gratour T3',
                'Gratour V5',
                'SAUVANA',
                'TOANO',
                'TUNLAND',
                'VIEW CS2'
            ],
            'Bomag' => [
                'BW BVC',
                'BW D-4',
                'BW D-40',
                'BW DH-4'
            ],
            'Tesla' => [
                'Model 3',
                'Model S',
                'Model X',
                'Model Y'
            ],
            'Паз' => [
                '3203',
                '3204',
                '3205',
                '32053',
                '32054',
                '4234'
            ],
            'Dongfeng' => [
                '370',
                '580',
                'A30',
                'A60',
                'A9',
                'AX3',
                'AX4',
                'AX5',
                'AX7',
                'Bus',
                'C31/C32',
                'C37',
                'CM7',
                'Captain',
                'Dollicar',
                'E70',
                'Glory 330',
                'Glory 360',
                'H30 CROSS',
                'Joyear LV',
                'Joyear X3',
                'Joyear X5',
                'Joyear XL',
                'Joyear XV',
                'K01S/K02S',
                'KC',
                'KL',
                'KR',
                'KX',
                'L60',
                'M3',
                'M5',
                'M600',
                'MX6',
                'Realing',
                'Rich',
                'S30',
                'S50',
                'S500',
                'SX6',
                'Special Truck',
                'Succe',
                'T5',
                'U-Vane',
                'V3'
            ],
            'Balkancar' => [
                'ER-2',
                'ER-3',
                'Record-1S',
                'Record-2S',
                'Record-2SR',
                'Record-3S',
                'Record-4S'
            ]
        ];

        foreach ($carBrands as $carBrand => $carModels) {
            $carBrandModel = CarBrand::whereName($carBrand)->first();

            if ($carBrandModel && is_array($carModels)) {
                foreach ($carModels as $carModel) {
                    CarModel::firstOrCreate([
                        'car_brand_id' => $carBrandModel->id,
                        'name' => $carModel,
                    ], [
                        'is_active' => true
                    ]);
                }
            }
        }
    }
}
